Repository Interactions-HSG/xarm-grpc, pull requests merged in 2021-08, with the labels that each got.

#11 refactor: with clang-tidy linter (resolves #9)
  .clang-format
  .clang-tidy
  README.md
  src/xarm-commander.cpp
Labels: refactor

#14 feat(GitHub): add clang-format and clan-lint Actions
  .github/actions/clang-format/Dockerfile
  .github/actions/clang-format/action.yml
  .github/actions/clang-format/entrypoint.sh
  .github/actions/clang-tidy/Dockerfile
  .github/actions/clang-tidy/action.yml
  .github/actions/clang-tidy/entrypoint.sh
  .github/workflows/format-lint.yml
  CODEOWNERS
  CONTRIBUTING.md
Labels: enhancement

#20 docs: fix CONTRINUTING.md and update README.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#24 chore: rename build to bin
  Makefile
Labels: refactor
