Repository Interactions-HSG/xarm-grpc, pull requests merged in 2021-11, with the labels that each got.

#50 style(proto): messages
  protos/xapi.proto
  xarm_grpc_service.cc
Labels: refactor

#49 Feat/affordance extension
  protos/xapi.proto
  tools/xarm-commander/xarm_commander.cc
  xarm_grpc_service.cc
Labels: enhancement

#52 fix(naming): change MotionEnable naming in xarm-grpc-service.cc
  xarm_grpc_service.cc
Labels: bug
